[versions]
kotlin = "2.2.10"
agp = "8.12.2"
junit5 = "5.11.2"

hyper-notification = "1.2"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }

hyper-notification-focus-api = { module = "com.xzakota.hyper.notification:focus-api", version.ref = "hyper-notification" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
